services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - AMBIENTE=development
    entrypoint:
      - /home/user/backend/entrypoint.sh
    depends_on:
      - db
      - pgadmin
    volumes:
      - ./backend/:/home/user/backend
    ports:
      - "8000:8000"

  db:
    build: ./postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_data:/tmp # Adjusted line

  pgadmin:
    image: dpage/pgadmin4
    ports: [ "5050:80" ]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  postgres_data:
